---
title: "Mapping US Presidential Election Results over Time"
output:
  pdf_document: default
  html_document:
    fig_caption: yes
---

The partisan identities of many states have been stable over time. For example, Massachusetts is a solidly ``blue'' state, having pledged its electoral votes to the Democratic candidate in 8 out of the last 10 presidential elections. On the other extreme, Arizona's electoral votes went to the Republican candidate in 9 of the same 10 elections. Still, geography can occasionally be a poor predictor of presidential elections. For instance, in 2008, typically red states -- including North Carolina, Indiana, and Virginia -- helped elect Barack Obama to the presidency.

------------------------------------------------------------------------------------------------------
 Name                 Description
 -------------------- --------------------------------------------------------------------------------
 `state`              Full name of 48 states (excluding Alaska, Hawaii, and the District of Columbia)
 
 `county`             County name
 
 `year`               Election year
 
 `rep`                Popular votes for the Republican candidate
 
 `dem`                Popular votes for the Democratic candidate
 
 `other`              Popular votes for other candidates
 ------------------------------------------------------------------------------------------------------
 
In this exercise, we will examine election results at the county level, allowing us to explore the spatial distribution of Democratic and Republican voters within states.  The data file is available in CSV format as `elections.csv`. Each row of the data set represents the distribution of votes in that year's presidential election from each county in the United States. The table above presents the names and descriptions of variables in this data set.

## Question 1

We begin by visualizing the outcome of the 2008 US presidential election at the county level. Begin with Massachusetts and Arizona and visualize the county-level outcome by coloring counties based on the two-party vote share. The color should range from pure blue (100\% Democratic) to pure red (100\% Republican) using the RGB color scheme.  Use the `county` database in the `maps` package.  The `regions` argument of the `map()` function enables us to specify the state and county.  The argument accepts a character vector, each entry of which has the syntax of `state, county`. Provide a brief comment.

## Answer 1

```{r}
par(cex = 1.5)

library(maps)
library(choroplethr)
library(choroplethrMaps)
library(dplyr)
library(ggplot2)


## I have downloaded fips codes from www.nrcs.usda.gov and created fips.csv so thtat I can add fips codes to the original dataset.
election <- read.csv("elections.csv") %>% data.frame()
fips <- read.csv("fips.csv") %>% data.frame()

## Checking if there is any NA
any(is.na(election))


## create a character vector of `state,county' inputs
## 2008 election
election <- election %>% 
  filter(year == 2008) %>%
  left_join(fips, by = "county")


## coloring based on two-party vote share
### If a value is greater than 0 in a county, the Republican candidate received more votes in the county.
### If a value is smaller than 0 in a county, the Democratic candidate received more votes in the county.
### Red indicates the Republican inclination, blue indicates the Democratic inclination, and the lighter the color is, the less the difference between the two parties was observed.
election <- data.frame(election) %>%
  mutate("total" = rep + dem + other) %>%
  mutate("rep_share" = rep/total) %>%
  mutate("dem_share" = dem/total) %>%
  mutate("value" = rep_share - dem_share) 



## initialize a map for Arizona
electionAZ <- election %>%
  filter(state == "arizona") %>%
  rename(region = fips)


AZ <- county_choropleth(electionAZ,
                  title      = "Outcome of the 2008 US Presidential Election: Arizona",
                  legend     = "value",
                  num_colors = 1,
                  state_zoom = "arizona")

AZ + scale_fill_gradient2(
  low = "#0033FF",
  mid = "white",
  high = "#CC0000",
  midpoint = 0,
  na.value = "grey50",
) +
  coord_map("ortho", orientation = c(40, -100, 0))+
  theme_minimal()


## initialize a map for Massachusetts
electionMA <- data.frame(election) %>%
  filter(state == "massachusetts") %>%
  rename(region = fips)


MA <- county_choropleth(electionMA,
                  title      = "Outcome of the 2008 US Presidential Election: Massachusetts",
                  legend     = "value",
                  num_colors = 1,
                  state_zoom = "massachusetts")

MA + scale_fill_gradient2(
  low = "#0033FF",
  mid = "white",
  high = "#CC0000",
  midpoint = 0,
  na.value = "grey50",
) +
  coord_map("ortho", orientation = c(40, -100, 0))+
  theme_minimal()

```


## My comment
In 2008, all counties of Massachusetts exhibited the predominant support for the Democrat candidate Barack Obama.On the other hand, Arizona's counties showed diverse political inclinations. The Republican candidate John McCain could receive the predominant support vis-a-vis Obama only in two counties. Considering that Arizona was known as McCain's "home turf," this outcome is surprising: Obama received more votes than McCain in four counties of Arizona.



